version: '2.4'                                                                                            
services:          
  bot:           
    build: ./bot
    environment:
      BOT_TOKEN: "123123:ABCD34asfasdasd"
      ADMIN_IDS: "1231231:2342344"
      PLACES: "Eckstraße:23:1232232,2342342;Kaiserstraße:52:2342123,4212321"     
      TRASH_URL: "https://.."
      PAPIER_URL: "https://../...ics"
      REDIS_HOST: "redis"

    volumes:
      - ./output:/output
    command: python /bot/trash.py                    
                                                     
    restart: unless-stopped                          
    networks:
      - external          
      - internal  
                          
    mem_limit: 192M       
    cpu_shares: 128                                  
    blkio_config:                                    
      weight: 200

  temp:
    build: ./bot
    environment:
      #FLASK_DEBUG: "1"
      REDIS_HOST: "redis"
    volumes:
      - ./socket:/var/www/socket

    command: ['uwsgi', '--ini', '/bot/mc-interface.ini']

    networks:
      - internal

    restart: unless-stopped

    mem_limit: 192M
    cpu_shares: 128
    blkio_config:
      weight: 200

  nginx:
    image: nginx:alpine

    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./htpasswd:/var/htpasswd:ro
      - ./uwsgi_params:/var/www/uwsgi_params:ro
      - ./socket:/socket
    networks:
      - external
      - internal
    ports:
      - "8080:80"

    restart: unless-stopped
    mem_limit: 128M
    cpu_shares: 128
    blkio_config:
      weight: 200

  redis:
    image: redis:alpine
    volumes:
      - ./redis-data:/data
    networks:
      - internal

    restart: unless-stopped
    mem_limit: 128M
    cpu_shares: 128
    blkio_config:
      weight: 200

networks:
  proxy_net:
    external: true
  internal:
    internal: true
  external:
